apiVersion: apps/v1
kind: Deployment
metadata:
  name: edit-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edit-models
  template:
    metadata:
      labels:
        app: edit-models
    spec:
      volumes:
      - name: stable-diffusion-models
        persistentVolumeClaim:
          claimName: comfyui-models-pvc # Need to sync all models in node's user-data
      containers:
      - name: tinyfilemanager
        image: tinyfilemanager/tinyfilemanager:master
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/data
          name: stable-diffusion-models
        # resources:
        #   requests:
        #     nvidia.com/gpu: 1
        #   limits:
        #     nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: edit-models-service
  labels:
    app: edit-models
spec:
  selector:
    app: edit-models
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30083
  type: NodePort
