apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-outputs-pvc
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi  # adjust the storage size as needed
