# ollama.yaml 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:  # <--- Add volume mounts
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:  # <--- Add volumes
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
      priorityClassName: system-node-critical  
  strategy:
    type: Recreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi  # adjust the storage size as needed

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service-node-port
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    nodePort: 31434
    protocol: TCP
  type: NodePort
