apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-osdisk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # adjust the storage size as needed
